export const LOAD_TRACKERS = 'LOAD_TRACKERS';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const ADD_NEW_TRACKER = 'ADD_NEW_TRACKER';
export const INCREMENT_TRACKER = 'INCREMENT_TRACKER';
export const UPDATE_TRACKER = 'UPDATE_TRACKER';